import type { Locale } from "@/lib/i18n";

export const siteCopy = {
  sl: {
    nav: {
      concept: "Koncept",
      process: "Proces",
      services: "Storitve",
      projects: "Projekti",
      content: "Vsebine",
      contact: "Kontakt",
      language: "Jezik",
      menu: "Meni",
      cta: "Odkrijte svoj Home DNA™",
    },
    hero: {
      headline: "Ne začnemo pri pohištvu. Začnemo pri ljudeh.",
      sub: "Nuveli Studio načrtuje interierje in pohištvo po meri za novogradnje in celovite prenove. Home DNA™ najprej zbere vaše navade, potrebe in okvir investicije.",
      primaryCta: "Odkrijte svoj Home DNA™ in dobite okvirno ponudbo",
      note: "Nekaj minut · brezplačno · brez obveznosti.",
      imageAlt: "Sodoben skandinavski interjer s hrastovim pohištvom po meri",
    },
    concept: {
      eyebrow: "Kaj upoštevamo",
      title: ["Kaj Home DNA™ upošteva.", "Preden začnemo oblikovati."],
      body: "Štiri skupine informacij neposredno vplivajo na razporeditev, shranjevanje in izbiro opreme.",
      imageAlt: "Detajl hrastovega mizarstva ob kamnitih tleh",
      points: [
        { title: "Kako živite", text: "Dnevne rutine, delo, kuhanje, druženje in počitek." },
        { title: "S kom živite", text: "Število odraslih in otrok ter potrebe, ki se bodo s časom spreminjale." },
        { title: "Kaj morate shraniti", text: "Oblačila, igrače, gospodinjski pripomočki in stvari, ki morajo ostati pri roki." },
        { title: "Kaj načrtujete", text: "Prihodnje spremembe družine, dela ali načina uporabe doma." },
      ],
    },
    process: {
      eyebrow: "Brezplačni prvi korak",
      title: "Od vprašanj do osebnega poročila",
      steps: [
        { step: "01", title: "Izpolnite Home DNA™", line: "V nekaj minutah opišete dom, navade in prioritete.", text: "Dodate prostore, slogovne preference, okvir investicije in želene materiale." },
        { step: "02", title: "Prejmete poročilo", line: "Vaši odgovori se pretvorijo v osebne smernice za dom.", text: "Poročilo povzame ključne potrebe, slogovno smer in priporočila po prostorih." },
        { step: "03", title: "Dobite okvirno ponudbo", line: "Prikažemo ocenjeni razpon investicije za izbrani obseg.", text: "Nato lahko izberete termin in skupaj preverimo naslednje korake." },
      ],
    },
    services: {
      eyebrow: "Obseg",
      title: "Kaj načrtujemo in izdelamo",
      items: [
        { title: "Kuhinja", text: "Razporeditev elementov, delovni tok, aparati, shranjevanje, osvetlitev in delovni pult." },
        { title: "Garderobe", text: "Notranja razporeditev po vaših oblačilih, policah, obešanju in sezonskem shranjevanju." },
        { title: "Bivalni prostori", text: "TV-elementi, knjižne omare, sedežne niše in shranjevanje z urejenimi prehodi." },
        { title: "Celoten dom", text: "Enoten načrt kuhinje, garderob, kopalniškega in bivalnega pohištva." },
      ],
      cta: "Pridobite okvirno ponudbo",
    },
    gallery: {
      eyebrow: "Projekti",
      title: "Življenja, prevedena v prostor",
      intro: "",
      projects: [
        "Kuhinja, oblikovana za petčlansko družino",
        "Dnevni prostor, oblikovan za družinsko življenje",
        "Garderoba, optimizirana za sezonska oblačila",
        "Skrito shranjevanje v vhodu za vsakodnevni red",
      ],
    },
    journey: {
      eyebrow: "Sodelovanje",
      title: "Od prvega pogovora do montaže",
      intro: "Jasen proces, ena kontaktna oseba in potrjene odločitve pred začetkom izdelave.",
      steps: [
        { title: "Prvi pogovor", text: "Preverimo prostore, želje, okvir investicije, želeni rok in primernost projekta." },
        { title: "Analiza Home DNA™", text: "Določimo prioritete gospodinjstva, potrebe po shranjevanju in funkcionalne zahteve." },
        { title: "Natančne meritve", text: "Na lokaciji izmerimo prostor, priključke in omejitve, ki vplivajo na izvedbo." },
        { title: "Oblikovanje", text: "Pripravimo razporeditev, izbor materialov in 3D prikaz pred potrditvijo." },
        { title: "Izvedba", text: "Po potrditvi izdelamo pohištvo, uskladimo dostavo in izvedemo montažo." },
        { title: "Predaja", text: "Skupaj pregledamo izvedbo in predamo prostor pripravljen za uporabo." },
      ],
    },
    content: {
      eyebrow: "Izbrani vodiči",
      title: "Odgovori pred začetkom projekta",
      intro: "Najpomembnejše informacije o Home DNA™, investiciji, kuhinjah po meri in poteku sodelovanja.",
      read: "Preberi celoten odgovor",
      all: "Vse vsebine",
    },
    contact: {
      eyebrow: "Kontakt",
      title: "Povejte nam, kaj opremljate",
      intro: "Opišite prostor, okvirni proračun in želeni rok. Odgovorimo v dveh delovnih dneh, nato izberete termin za pogovor.",
      name: "Ime",
      namePlaceholder: "Vaše ime in priimek",
      email: "E-pošta",
      emailPlaceholder: "vi@eposta.si",
      phone: "Telefon",
      projectType: "Vrsta projekta",
      choose: "Izberite",
      inspiration: "Slike za navdih",
      upload: "Naložite slike",
      selectedFiles: (count: number) => `Izbranih datotek: ${count}`,
      message: "Sporočilo",
      messagePlaceholder: "Povejte nam o svojem domu, časovnici in kaj želite rešiti.",
      submit: "Nadaljujte na izbiro termina",
      bookingHeading: "Izberite termin za osebni pogovor",
      bookingDescription: "Vaši kontaktni podatki so pripravljeni. Za dokončanje rezervacije izberite način srečanja, datum in uro.",
      validationName: "Vnesite svoje ime",
      validationEmail: "Vnesite veljaven e-naslov",
      validationProject: "Izberite vrsto projekta",
      projectTypes: ["Opremljanje celotnega doma", "Kuhinja", "Garderobna omara", "Pohodna garderoba", "Kopalniško pohištvo", "Dnevni prostor"],
    },
    footer: {
      text: "Domovi, oblikovani okoli načina, kako živite.",
      address: "Ljubljana, Slovenija",
    },
  },
  hr: {
    nav: {
      concept: "Koncept",
      process: "Proces",
      services: "Usluge",
      projects: "Projekti",
      content: "Sadržaj",
      contact: "Kontakt",
      language: "Jezik",
      menu: "Izbornik",
      cta: "Otkrijte svoj Home DNA™",
    },
    hero: {
      headline: "Ne počinjemo namještajem. Počinjemo ljudima.",
      sub: "Nuveli Studio projektira interijere i namještaj po mjeri za novogradnje i potpune renovacije. Home DNA™ najprije prikuplja vaše navike, potrebe i okvir ulaganja.",
      primaryCta: "Otkrijte svoj Home DNA™ i dobijte okvirnu ponudu",
      note: "Nekoliko minuta · besplatno · bez obveze.",
      imageAlt: "Suvremen skandinavski interijer s namještajem po mjeri od hrasta",
    },
    concept: {
      eyebrow: "Što uzimamo u obzir",
      title: ["Što Home DNA™ uzima u obzir.", "Prije početka projektiranja."],
      body: "Četiri skupine informacija izravno utječu na raspored, spremanje i odabir opreme.",
      imageAlt: "Detalj hrastove stolarije uz kameni pod",
      points: [
        { title: "Kako živite", text: "Dnevne rutine, rad, kuhanje, druženje i odmor." },
        { title: "S kim živite", text: "Broj odraslih i djece te potrebe koje će se s vremenom mijenjati." },
        { title: "Što trebate spremiti", text: "Odjeća, igračke, kućanski pribor i stvari koje moraju ostati nadohvat ruke." },
        { title: "Što planirate", text: "Buduće promjene obitelji, rada ili načina korištenja doma." },
      ],
    },
    process: {
      eyebrow: "Besplatan prvi korak",
      title: "Od pitanja do osobnog izvještaja",
      steps: [
        { step: "01", title: "Ispunite Home DNA™", line: "U nekoliko minuta opišete dom, navike i prioritete.", text: "Dodate prostorije, stilske preferencije, okvir ulaganja i željene materijale." },
        { step: "02", title: "Primite izvještaj", line: "Vaši se odgovori pretvaraju u osobne smjernice za dom.", text: "Izvještaj sažima ključne potrebe, stilsku usmjerenost i preporuke po prostorijama." },
        { step: "03", title: "Dobijete okvirnu ponudu", line: "Prikazujemo procijenjeni raspon ulaganja za odabrani opseg.", text: "Zatim možete odabrati termin i zajedno provjeravamo sljedeće korake." },
      ],
    },
    services: {
      eyebrow: "Opseg",
      title: "Što projektiramo i izrađujemo",
      items: [
        { title: "Kuhinja", text: "Raspored elemenata, tijek rada, uređaji, spremanje, rasvjeta i radna ploča." },
        { title: "Garderobe", text: "Unutarnji raspored prema vašoj odjeći, policama, vješanju i sezonskom spremanju." },
        { title: "Dnevni prostori", text: "TV-elementi, police za knjige, sjedeće niše i spremanje s uređenim prolazima." },
        { title: "Cijeli dom", text: "Jedinstven plan kuhinje, garderoba, kupaonskog i dnevnog namještaja." },
      ],
      cta: "Zatražite okvirnu ponudu",
    },
    gallery: {
      eyebrow: "Projekti",
      title: "Životi prevedeni u prostor",
      intro: "",
      projects: [
        "Kuhinja oblikovana za peteročlanu obitelj",
        "Dnevni prostor oblikovan za obiteljski život",
        "Garderoba optimizirana za sezonsku odjeću",
        "Skriveno spremanje u ulazu za svakodnevni red",
      ],
    },
    journey: {
      eyebrow: "Suradnja",
      title: "Od prvog razgovora do montaže",
      intro: "Jasan proces, jedna kontaktna osoba i potvrđene odluke prije početka izrade.",
      steps: [
        { title: "Prvi razgovor", text: "Provjeravamo prostorije, želje, okvir ulaganja, željeni rok i prikladnost projekta." },
        { title: "Home DNA™ analiza", text: "Određujemo prioritete kućanstva, potrebe za spremanjem i funkcionalne zahtjeve." },
        { title: "Precizna mjerenja", text: "Na lokaciji mjerimo prostor, priključke i ograničenja koja utječu na izvedbu." },
        { title: "Oblikovanje", text: "Pripremamo raspored, izbor materijala i 3D prikaz prije potvrde." },
        { title: "Izvedba", text: "Nakon potvrde izrađujemo namještaj, usklađujemo dostavu i izvodimo montažu." },
        { title: "Primopredaja", text: "Zajedno pregledavamo izvedbu i predajemo prostor spreman za korištenje." },
      ],
    },
    content: {
      eyebrow: "Odabrani vodiči",
      title: "Odgovori prije početka projekta",
      intro: "Najvažnije informacije o Home DNA™, ulaganju, kuhinjama po mjeri i tijeku suradnje.",
      read: "Pročitajte cijeli odgovor",
      all: "Sav sadržaj",
    },
    contact: {
      eyebrow: "Kontakt",
      title: "Recite nam što opremate",
      intro: "Opišite prostor, okvirni budžet i željeni rok. Odgovaramo u roku od dva radna dana, zatim odabirete termin za razgovor.",
      name: "Ime",
      namePlaceholder: "Ime i prezime",
      email: "E-mail",
      emailPlaceholder: "vi@email.com",
      phone: "Telefon",
      projectType: "Vrsta projekta",
      choose: "Odaberite",
      inspiration: "Slike za inspiraciju",
      upload: "Učitajte slike",
      selectedFiles: (count: number) => `Odabrane datoteke: ${count}`,
      message: "Poruka",
      messagePlaceholder: "Recite nam nešto o svom domu, vremenskom okviru i onome što želite riješiti.",
      submit: "Nastavite na odabir termina",
      bookingHeading: "Odaberite termin za osobni razgovor",
      bookingDescription: "Vaši kontaktni podaci su spremni. Za dovršetak rezervacije odaberite način sastanka, datum i vrijeme.",
      validationName: "Unesite svoje ime",
      validationEmail: "Unesite valjanu e-mail adresu",
      validationProject: "Odaberite vrstu projekta",
      projectTypes: ["Uređenje cijelog doma", "Kuhinja", "Garderobni ormar", "Walk-in garderoba", "Kupaonski namještaj", "Dnevni prostor"],
    },
    footer: {
      text: "Domovi oblikovani oko načina na koji živite.",
      address: "Ljubljana, Slovenija",
    },
  },
  en: {
    nav: {
      concept: "Concept",
      process: "Process",
      services: "Services",
      projects: "Projects",
      content: "Guides",
      contact: "Contact",
      language: "Language",
      menu: "Menu",
      cta: "Discover your Home DNA™",
    },
    hero: {
      headline: "We don't start with furniture. We start with people.",
      sub: "Nuveli Studio designs bespoke interiors and furniture for new builds and full renovations. Home DNA™ first captures your routines, needs and investment range.",
      primaryCta: "Discover your Home DNA™ and get an indicative quote",
      note: "A few minutes · free · no obligation.",
      imageAlt: "Contemporary Scandinavian interior with bespoke oak cabinetry",
    },
    concept: {
      eyebrow: "What we consider",
      title: ["What Home DNA™ considers.", "Before design begins."],
      body: "Four groups of information directly shape the layout, storage and specification.",
      imageAlt: "Detail of bespoke oak joinery beside a stone floor",
      points: [
        { title: "How you live", text: "Daily routines, work, cooking, time together and rest." },
        { title: "Who you live with", text: "The number of adults and children, and needs that will change over time." },
        { title: "What you need to store", text: "Clothes, toys, household equipment and items that must remain within reach." },
        { title: "What you are planning", text: "Future changes to your family, work or how you use your home." },
      ],
    },
    process: {
      eyebrow: "Free first step",
      title: "From questions to your personal report",
      steps: [
        { step: "01", title: "Complete Home DNA™", line: "Describe your home, routines and priorities in a few minutes.", text: "Add rooms, style preferences, your investment range and preferred materials." },
        { step: "02", title: "Receive your report", line: "Your answers become personal guidance for your home.", text: "The report summarises key needs, style direction and room-by-room recommendations." },
        { step: "03", title: "Get an indicative quote", line: "See an estimated investment range for your selected scope.", text: "You can then choose a consultation time and review the next steps with us." },
      ],
    },
    services: {
      eyebrow: "Scope",
      title: "What we design and make",
      items: [
        { title: "Kitchen", text: "Cabinet layout, workflow, appliances, storage, lighting and worktops." },
        { title: "Wardrobes", text: "Internal layouts based on your clothes, shelving, hanging space and seasonal storage." },
        { title: "Living spaces", text: "Media units, bookcases, seating niches and storage with clear circulation." },
        { title: "Whole home", text: "One coordinated plan for kitchens, wardrobes, bathrooms and living spaces." },
      ],
      cta: "Get an indicative quote",
    },
    gallery: {
      eyebrow: "Projects",
      title: "Lives translated into space",
      intro: "",
      projects: [
        "Kitchen designed for a family of five",
        "Living room designed for family life",
        "Wardrobe optimised for seasonal clothing",
        "Concealed entry storage for everyday order",
      ],
    },
    journey: {
      eyebrow: "Working together",
      title: "From first conversation to installation",
      intro: "A clear process, one point of contact and confirmed decisions before production begins.",
      steps: [
        { title: "First conversation", text: "We review the rooms, requirements, investment range, desired timeline and project fit." },
        { title: "Home DNA™ analysis", text: "We define household priorities, storage needs and functional requirements." },
        { title: "Precise measurements", text: "We measure the space, services and constraints that affect delivery." },
        { title: "Design", text: "We prepare the layout, material selection and 3D visuals for approval." },
        { title: "Execution", text: "After approval, we make the furniture, coordinate delivery and complete installation." },
        { title: "Handover", text: "We inspect the finished work together and hand over a space ready to use." },
      ],
    },
    content: {
      eyebrow: "Selected guides",
      title: "Answers before your project begins",
      intro: "Essential information about Home DNA™, investment, bespoke kitchens and how we work.",
      read: "Read the full answer",
      all: "All guides",
    },
    contact: {
      eyebrow: "Contact",
      title: "Tell us what you are furnishing",
      intro: "Describe the space, your indicative budget and desired timeline. We reply within two working days, then you choose a consultation time.",
      name: "Name",
      namePlaceholder: "Your full name",
      email: "Email",
      emailPlaceholder: "you@email.com",
      phone: "Phone",
      projectType: "Project type",
      choose: "Choose",
      inspiration: "Inspiration images",
      upload: "Upload images",
      selectedFiles: (count: number) => `Selected files: ${count}`,
      message: "Message",
      messagePlaceholder: "Tell us about your home, timeline and what you would like to solve.",
      submit: "Continue to appointment selection",
      bookingHeading: "Choose a time for a personal conversation",
      bookingDescription: "Your contact details are ready. To complete the booking, choose the meeting type, date and time.",
      validationName: "Enter your name",
      validationEmail: "Enter a valid email address",
      validationProject: "Choose a project type",
      projectTypes: ["Whole-home interior", "Kitchen", "Wardrobe", "Walk-in wardrobe", "Bathroom furniture", "Living space"],
    },
    footer: {
      text: "Homes designed around the way you live.",
      address: "Ljubljana, Slovenia",
    },
  },
} as const;

export function getSiteCopy(locale: Locale) {
  return siteCopy[locale];
}
