import type { Locale } from "@/lib/i18n";

export const siteCopy = {
  sl: {
    nav: {
      concept: "Koncept",
      process: "Proces",
      services: "Storitve",
      projects: "Projekti",
      content: "Vsebine",
      contact: "Kontakt",
      language: "Jezik",
      menu: "Meni",
      cta: "Odkrijte svoj Home DNA™",
    },
    hero: {
      headline: "Ne začnemo pri pohištvu. Začnemo pri ljudeh.",
      sub: "Nuveli Studio oblikuje pohištvo domov okoli načina, kako živite — z metodologijo Home DNA™, s katero razumemo vsakdan, preden karkoli narišemo.",
      primaryCta: "Odkrijte svoj Home DNA™",
      secondaryCta: "Poglejte, kako ljudje živijo",
      note: "Brezplačen osebni Home DNA™ Report + okvirna ponudba za izbrani obseg projekta.",
      imageAlt: "Sodoben skandinavski interjer s hrastovim pohištvom po meri",
    },
    concept: {
      eyebrow: "Filozofija",
      title: ["Dom naj sledi vašemu življenju.", "Ne obratno."],
      body: "Večina interjerjev se začne z načrtom prostora. Naši se začnejo z ljudmi v njem — z njihovimi jutri, večeri, stvarmi in prihodnjimi leti. Vse, kar oblikujemo, je posledica tega razumevanja.",
      imageAlt: "Detajl hrastovega mizarstva ob kamnitih tleh",
      points: [
        { title: "Kako živite", text: "Navade, ki tiho oblikujejo vsako jutro in vsak večer." },
        { title: "S kom živite", text: "Kdo je doma danes in kdo bo jutri." },
        { title: "Kaj imate", text: "Vse, kar je že del vašega življenja, razumljeno in postavljeno na svoje mesto." },
        { title: "Kam gre življenje", text: "Kako naj vam dom ustreza tudi čez deset let." },
      ],
    },
    process: {
      eyebrow: "Metodologija",
      title: "Proces Home DNA™",
      steps: [
        { step: "01", title: "Razumemo", line: "Vsak projekt se začne s Home DNA™.", text: "Preden karkoli oblikujemo, analiziramo vaš življenjski slog, navade, potrebe po shranjevanju in načrte za prihodnost." },
        { step: "02", title: "Oblikujemo", line: "Vaše potrebe prevedemo v inteligenten prostor.", text: "Vsak centimeter dobi svojo nalogo, prikazan v natančni 3D vizualizaciji pred izdelavo." },
        { step: "03", title: "Izdelamo", line: "Natančna izdelava in profesionalna montaža.", text: "Izdelano do milimetra natančno, montirano s strani iste ekipe, ki je projekt zasnovala." },
        { step: "04", title: "Živite", line: "Dom, kjer ima vsaka stvar svoje mesto in vsak trenutek svoj prostor.", text: "Rezultat je tih: nič ne manjka, nič ni napoti." },
      ],
    },
    services: {
      eyebrow: "Rezultat",
      title: "Kako Home DNA™ zaživi v prostoru",
      items: [
        { title: "Kuhinja", text: "Premišljen potek dela, prava razmerja in vse pri roki, ko to potrebujete." },
        { title: "Garderobe", text: "Pregleden sistem shranjevanja, prilagojen vaši garderobi in vsakodnevnemu ritmu." },
        { title: "Bivalni prostori", text: "Uravnotežen prostor za skupne trenutke, miren oddih in vse vmes." },
        { title: "Celoten dom", text: "Materiali, funkcije in detajli, povezani v skladno celoto." },
      ],
    },
    gallery: {
      eyebrow: "Domovi, ki smo jih razumeli",
      title: "Življenja, prevedena v prostor",
      intro: "Vsak projekt se je začel enako: pri ljudeh, ki v njem živijo.",
      projects: [
        "Kuhinja, oblikovana za petčlansko družino",
        "Dnevni prostor, oblikovan za družinsko življenje",
        "Garderoba, optimizirana za sezonska oblačila",
        "Skrito shranjevanje v vhodu za vsakodnevni red",
      ],
    },
    journey: {
      eyebrow: "Pot",
      title: "Od prvega pogovora do vsakdanjega življenja",
      intro: "En studio, ena ekipa, eno razumevanje vašega doma — skozi vse faze.",
      steps: [
        { title: "Prvi pogovor", text: "Srečamo se, poslušamo in razumemo, kako izgleda vsakdan v vašem domu." },
        { title: "Analiza Home DNA™", text: "Navade, stvari in načrti za prihodnost, prevedeni v način življenja." },
        { title: "Natančne meritve", text: "Obstoječi prostor, razumljen do milimetra natančno." },
        { title: "Oblikovanje", text: "Vaš vsakdan, narisan v prostor, materiale in svetlobo." },
        { title: "Izvedba", text: "Izdelano s skrbnostjo, v nadzorovanih pogojih, s strani ljudi, ki projekt poznajo." },
        { title: "Predaja", text: "Trenutek, ko vaš dom začne tiho delovati za vas." },
      ],
      benefits: [
        { title: "Najprej ljudje", text: "Oblikujemo okoli življenj, nikoli okoli katalogov." },
        { title: "Prostor za vse", text: "Shranjevanje, oblikovano po tem, kar zares imate." },
        { title: "Tiha natančnost", text: "Premišljeno do milimetra, občuteno vsak dan." },
        { title: "En partner", text: "Od prvega pogovora do zadnjega detajla." },
      ],
    },
    content: {
      eyebrow: "Nuveli Studio · Vsebine",
      title: "Vprašanja, ki si jih zastavi skoraj vsak pri opremljanju doma",
      intro: "Kratki, konkretni odgovori o načrtovanju interierja, pohištvu po meri, materialih, investiciji in Home DNA™ metodologiji.",
      read: "Preberi celoten odgovor",
      all: "Vse vsebine",
    },
    contact: {
      eyebrow: "Kontakt",
      title: "Začnimo pri vašem življenju",
      intro: "Povejte nam, kako živite. Odgovorimo v dveh delovnih dneh in se dogovorimo za osebni pogovor.",
      name: "Ime",
      namePlaceholder: "Vaše ime in priimek",
      email: "E-pošta",
      emailPlaceholder: "vi@eposta.si",
      phone: "Telefon",
      projectType: "Vrsta projekta",
      choose: "Izberite",
      inspiration: "Slike za navdih",
      upload: "Naložite slike",
      selectedFiles: (count: number) => `Izbranih datotek: ${count}`,
      message: "Sporočilo",
      messagePlaceholder: "Povejte nam o svojem domu, časovnici in kaj želite rešiti.",
      submit: "Nadaljujte na izbiro termina",
      bookingHeading: "Izberite termin za osebni pogovor",
      bookingDescription: "Vaši kontaktni podatki so pripravljeni. Za dokončanje rezervacije izberite način srečanja, datum in uro.",
      validationName: "Vnesite svoje ime",
      validationEmail: "Vnesite veljaven e-naslov",
      validationProject: "Izberite vrsto projekta",
      projectTypes: ["Opremljanje celotnega doma", "Kuhinja", "Garderobna omara", "Pohodna garderoba", "Kopalniško pohištvo", "Dnevni prostor"],
    },
    footer: {
      text: "Domovi, oblikovani okoli načina, kako živite.",
      address: "Ljubljana, Slovenija",
    },
  },
  hr: {
    nav: {
      concept: "Koncept",
      process: "Proces",
      services: "Usluge",
      projects: "Projekti",
      content: "Sadržaj",
      contact: "Kontakt",
      language: "Jezik",
      menu: "Izbornik",
      cta: "Otkrijte svoj Home DNA™",
    },
    hero: {
      headline: "Ne počinjemo namještajem. Počinjemo ljudima.",
      sub: "Nuveli Studio oblikuje interijere i namještaj oko načina na koji živite — metodologijom Home DNA™ razumijemo svakodnevicu prije nego što išta nacrtamo.",
      primaryCta: "Otkrijte svoj Home DNA™",
      secondaryCta: "Pogledajte kako ljudi žive",
      note: "Besplatan osobni Home DNA™ Report + okvirna ponuda za odabrani opseg projekta.",
      imageAlt: "Suvremen skandinavski interijer s namještajem po mjeri od hrasta",
    },
    concept: {
      eyebrow: "Filozofija",
      title: ["Dom treba pratiti vaš život.", "Ne obrnuto."],
      body: "Većina interijera počinje tlocrtom. Naši počinju ljudima koji u prostoru žive — njihovim jutrima, večerima, stvarima i godinama koje dolaze. Sve što oblikujemo proizlazi iz tog razumijevanja.",
      imageAlt: "Detalj hrastove stolarije uz kameni pod",
      points: [
        { title: "Kako živite", text: "Navike koje tiho oblikuju svako jutro i svaku večer." },
        { title: "S kim živite", text: "Tko je kod kuće danas i tko će biti sutra." },
        { title: "Što imate", text: "Sve što je već dio vašeg života, shvaćeno i smješteno na svoje mjesto." },
        { title: "Kamo život ide", text: "Kako dom treba odgovarati vašim potrebama i za deset godina." },
      ],
    },
    process: {
      eyebrow: "Metodologija",
      title: "Proces Home DNA™",
      steps: [
        { step: "01", title: "Razumijemo", line: "Svaki projekt počinje s Home DNA™.", text: "Prije oblikovanja analiziramo vaš životni stil, navike, potrebe za spremanjem i planove za budućnost." },
        { step: "02", title: "Oblikujemo", line: "Vaše potrebe prevodimo u inteligentan prostor.", text: "Svaki centimetar dobiva svoju ulogu, prikazanu u preciznoj 3D vizualizaciji prije izrade." },
        { step: "03", title: "Izrađujemo", line: "Precizna izrada i profesionalna montaža.", text: "Izvedeno do milimetra i montirano od strane tima koji je projekt osmislio." },
        { step: "04", title: "Živite", line: "Dom u kojem sve ima svoje mjesto.", text: "Rezultat je tih: ništa ne nedostaje i ništa ne smeta." },
      ],
    },
    services: {
      eyebrow: "Rezultat",
      title: "Kako Home DNA™ oživi u prostoru",
      items: [
        { title: "Kuhinja", text: "Promišljen tijek rada, pravi omjeri i sve pri ruci kada vam treba." },
        { title: "Garderobe", text: "Pregledan sustav spremanja prilagođen vašoj garderobi i dnevnom ritmu." },
        { title: "Dnevni prostori", text: "Uravnotežen prostor za zajedničke trenutke, miran odmor i sve između." },
        { title: "Cijeli dom", text: "Materijali, funkcije i detalji povezani u skladnu cjelinu." },
      ],
    },
    gallery: {
      eyebrow: "Domovi koje smo razumjeli",
      title: "Životi prevedeni u prostor",
      intro: "Svaki je projekt počeo jednako: ljudima koji u njemu žive.",
      projects: [
        "Kuhinja oblikovana za peteročlanu obitelj",
        "Dnevni prostor oblikovan za obiteljski život",
        "Garderoba optimizirana za sezonsku odjeću",
        "Skriveno spremanje u ulazu za svakodnevni red",
      ],
    },
    journey: {
      eyebrow: "Put",
      title: "Od prvog razgovora do svakodnevnog života",
      intro: "Jedan studio, jedan tim, jedno razumijevanje vašeg doma — kroz sve faze.",
      steps: [
        { title: "Prvi razgovor", text: "Susrećemo se, slušamo i razumijemo kako izgleda svakodnevica u vašem domu." },
        { title: "Home DNA™ analiza", text: "Navike, stvari i planovi za budućnost prevedeni u način života." },
        { title: "Precizna mjerenja", text: "Postojeći prostor shvaćen do milimetra." },
        { title: "Oblikovanje", text: "Vaša svakodnevica nacrtana kroz prostor, materijale i svjetlo." },
        { title: "Izvedba", text: "Izrađeno pažljivo, u kontroliranim uvjetima, od ljudi koji poznaju projekt." },
        { title: "Primopredaja", text: "Trenutak kada vaš dom počinje tiho raditi za vas." },
      ],
      benefits: [
        { title: "Ljudi prije svega", text: "Oblikujemo oko života, nikada oko kataloga." },
        { title: "Mjesto za sve", text: "Spremanje oblikovano prema onome što stvarno imate." },
        { title: "Tiha preciznost", text: "Promišljeno do milimetra, osjetljivo svaki dan." },
        { title: "Jedan partner", text: "Od prvog razgovora do posljednjeg detalja." },
      ],
    },
    content: {
      eyebrow: "Nuveli Studio · Sadržaj",
      title: "Pitanja koja si gotovo svatko postavlja pri uređenju doma",
      intro: "Kratki i konkretni odgovori o planiranju interijera, namještaju po mjeri, materijalima, investiciji i Home DNA™ metodologiji.",
      read: "Pročitajte cijeli odgovor",
      all: "Sav sadržaj",
    },
    contact: {
      eyebrow: "Kontakt",
      title: "Počnimo vašim načinom života",
      intro: "Recite nam kako živite. Odgovaramo u roku od dva radna dana i dogovaramo osobni razgovor.",
      name: "Ime",
      namePlaceholder: "Ime i prezime",
      email: "E-mail",
      emailPlaceholder: "vi@email.com",
      phone: "Telefon",
      projectType: "Vrsta projekta",
      choose: "Odaberite",
      inspiration: "Slike za inspiraciju",
      upload: "Učitajte slike",
      selectedFiles: (count: number) => `Odabrane datoteke: ${count}`,
      message: "Poruka",
      messagePlaceholder: "Recite nam nešto o svom domu, vremenskom okviru i onome što želite riješiti.",
      submit: "Nastavite na odabir termina",
      bookingHeading: "Odaberite termin za osobni razgovor",
      bookingDescription: "Vaši kontaktni podaci su spremni. Za dovršetak rezervacije odaberite način sastanka, datum i vrijeme.",
      validationName: "Unesite svoje ime",
      validationEmail: "Unesite valjanu e-mail adresu",
      validationProject: "Odaberite vrstu projekta",
      projectTypes: ["Uređenje cijelog doma", "Kuhinja", "Garderobni ormar", "Walk-in garderoba", "Kupaonski namještaj", "Dnevni prostor"],
    },
    footer: {
      text: "Domovi oblikovani oko načina na koji živite.",
      address: "Ljubljana, Slovenija",
    },
  },
  en: {
    nav: {
      concept: "Concept",
      process: "Process",
      services: "Services",
      projects: "Projects",
      content: "Guides",
      contact: "Contact",
      language: "Language",
      menu: "Menu",
      cta: "Discover your Home DNA™",
    },
    hero: {
      headline: "We don't start with furniture. We start with people.",
      sub: "Nuveli Studio designs interiors and custom furniture around the way you live — with Home DNA™, we understand everyday life before we draw anything.",
      primaryCta: "Discover your Home DNA™",
      secondaryCta: "See how people live",
      note: "Free personal Home DNA™ Report + indicative quotation for your selected project scope.",
      imageAlt: "Contemporary Scandinavian interior with bespoke oak cabinetry",
    },
    concept: {
      eyebrow: "Philosophy",
      title: ["Your home should follow your life.", "Not the other way around."],
      body: "Most interiors begin with a floor plan. Ours begin with the people who live there — their mornings, evenings, belongings and the years ahead. Everything we design follows from that understanding.",
      imageAlt: "Detail of bespoke oak joinery beside a stone floor",
      points: [
        { title: "How you live", text: "The habits that quietly shape every morning and evening." },
        { title: "Who you live with", text: "Who is at home today and who may be there tomorrow." },
        { title: "What you have", text: "Everything already part of your life, understood and given its place." },
        { title: "Where life is going", text: "How your home should still work for you ten years from now." },
      ],
    },
    process: {
      eyebrow: "Methodology",
      title: "The Home DNA™ process",
      steps: [
        { step: "01", title: "Understand", line: "Every project begins with Home DNA™.", text: "Before designing anything, we analyse your lifestyle, routines, storage needs and plans for the future." },
        { step: "02", title: "Design", line: "We translate your needs into an intelligent space.", text: "Every centimetre gets a purpose, shown in a precise 3D visualisation before production." },
        { step: "03", title: "Make", line: "Precise production and professional installation.", text: "Made to the millimetre and installed by the same team that developed the project." },
        { step: "04", title: "Live", line: "A home where everything has its place.", text: "The result is quiet: nothing is missing and nothing gets in the way." },
      ],
    },
    services: {
      eyebrow: "Result",
      title: "How Home DNA™ comes to life in your space",
      items: [
        { title: "Kitchen", text: "Thoughtful workflow, the right proportions and everything within reach when you need it." },
        { title: "Wardrobes", text: "Clear storage systems tailored to your wardrobe and daily rhythm." },
        { title: "Living spaces", text: "Balanced spaces for time together, quiet rest and everything in between." },
        { title: "Whole home", text: "Materials, functions and details connected into one coherent interior." },
      ],
    },
    gallery: {
      eyebrow: "Homes we understood",
      title: "Lives translated into space",
      intro: "Every project began in the same place: with the people who live there.",
      projects: [
        "Kitchen designed for a family of five",
        "Living room designed for family life",
        "Wardrobe optimised for seasonal clothing",
        "Concealed entry storage for everyday order",
      ],
    },
    journey: {
      eyebrow: "Journey",
      title: "From the first conversation to everyday life",
      intro: "One studio, one team, one understanding of your home — through every stage.",
      steps: [
        { title: "First conversation", text: "We meet, listen and understand what everyday life in your home really looks like." },
        { title: "Home DNA™ analysis", text: "Habits, belongings and future plans translated into a way of living." },
        { title: "Precise measurements", text: "Your existing space understood down to the millimetre." },
        { title: "Design", text: "Your everyday life drawn into space, materials and light." },
        { title: "Execution", text: "Made with care, in controlled conditions, by people who know the project." },
        { title: "Handover", text: "The moment your home begins to quietly work for you." },
      ],
      benefits: [
        { title: "People first", text: "We design around lives, never around catalogues." },
        { title: "A place for everything", text: "Storage designed around what you actually own." },
        { title: "Quiet precision", text: "Considered to the millimetre, felt every day." },
        { title: "One partner", text: "From the first conversation to the final detail." },
      ],
    },
    content: {
      eyebrow: "Nuveli Studio · Guides",
      title: "Questions almost everyone asks when furnishing a home",
      intro: "Short, practical answers about interior planning, bespoke furniture, materials, investment and the Home DNA™ methodology.",
      read: "Read the full answer",
      all: "All guides",
    },
    contact: {
      eyebrow: "Contact",
      title: "Let's start with the way you live",
      intro: "Tell us how you live. We reply within two working days and arrange a personal conversation.",
      name: "Name",
      namePlaceholder: "Your full name",
      email: "Email",
      emailPlaceholder: "you@email.com",
      phone: "Phone",
      projectType: "Project type",
      choose: "Choose",
      inspiration: "Inspiration images",
      upload: "Upload images",
      selectedFiles: (count: number) => `Selected files: ${count}`,
      message: "Message",
      messagePlaceholder: "Tell us about your home, timeline and what you would like to solve.",
      submit: "Continue to appointment selection",
      bookingHeading: "Choose a time for a personal conversation",
      bookingDescription: "Your contact details are ready. To complete the booking, choose the meeting type, date and time.",
      validationName: "Enter your name",
      validationEmail: "Enter a valid email address",
      validationProject: "Choose a project type",
      projectTypes: ["Whole-home interior", "Kitchen", "Wardrobe", "Walk-in wardrobe", "Bathroom furniture", "Living space"],
    },
    footer: {
      text: "Homes designed around the way you live.",
      address: "Ljubljana, Slovenia",
    },
  },
} as const;

export function getSiteCopy(locale: Locale) {
  return siteCopy[locale];
}
